# Generated by Django 3.0.8 on 2020-07-06 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('currrent_price', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('local_url', models.CharField(blank=True, max_length=255, unique=True)),
                ('store', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Zapatilla',
                'verbose_name_plural': 'Zapatillas',
                'ordering': ['name'],
                'unique_together': {('description', 'price')},
            },
        ),
    ]
