# Generated by Django 3.0.8 on 2020-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='local_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='store',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
