# Generated by Django 3.0.8 on 2020-07-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200702_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zapatilla',
            unique_together={('name', 'local_url')},
        ),
    ]
