# Generated by Django 3.0.8 on 2020-07-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200703_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zapatilla',
            unique_together=set(),
        ),
    ]
