# Generated by Django 3.0.8 on 2020-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20200703_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
