# Generated by Django 3.0.8 on 2020-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200703_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='local_url',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='zapatilla',
            unique_together={('description', 'price')},
        ),
    ]
